### ISSUE TITLE
crates not working :S everything else is fine?

### ISSUE THREAD

**Issue by chillerkraft** [AJCStriker/Movecraft-3#137]
im hoping i can eventually be able to use the crates provided by this plugin for more places then just crafts.. i just mainly want to have the crate blocks for looks on my server but usage would be nice to,
is this at all possible? here's the error im getting

23.12 00:10:12 [Server] INFO Admins: ChillerKraft
23.12 00:10:06 [Server] INFO ... 17 more
23.12 00:10:06 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
23.12 00:10:06 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
23.12 00:10:06 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
23.12 00:10:06 [Server] INFO at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[?:?]
23.12 00:10:06 [Server] INFO at net.countercraft.movecraft.listener.BlockListener.onBlockPlace(BlockListener.java:47) ~[?:?]
23.12 00:10:06 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.createNewInventory(StorageChestItem.java:64) ~[?:?]
23.12 00:10:06 [Server] INFO Caused by: java.lang.NullPointerException
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:629) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:390) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at net.minecraft.server.v1_7_R3.ItemStack.placeItem(ItemStack.java:142) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:138) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins.jar:?]
23.12 00:10:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.7.9-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
23.12 00:10:06 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
23.12 00:10:06 [Server] INFO org.bukkit.event.EventException
23.12 00:10:06 [Server] INFO Could not pass event BlockPlaceEvent to Movecraft v3.1.X54
23.12 00:10:06 [Server] ERROR ***\* THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****

**Comment by eirikh1996** [comment]
I also have a problem. I can craft a storage crate, however, when I place it, it turns into a non-sticky piston. At the same time the following error occures:

[23:05:03 WARN]: [Movecraft] Task #2891 for Movecraft v3.1.X73 generated an exception
java.lang.IllegalArgumentException: Cannot set property BlockStateDirection{name=facing, clazz=class net.minecraft.server.v1_8_R1.EnumDirection, values=[down, up, north, south, west, east]} to null on block minecraft:piston, it is not an allowed value
	at net.minecraft.server.v1_8_R1.BlockData.set(SourceFile:124) ~[spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.BlockPiston.fromLegacyData(BlockPiston.java:412) ~[spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.craftbukkit.v1_8_R1.block.CraftBlock.setData(CraftBlock.java:107) ~[spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.craftbukkit.v1_8_R1.block.CraftBlock.setData(CraftBlock.java:92) ~[spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.countercraft.movecraft.listener.BlockListener$1.run(BlockListener.java:78) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot_server.jar:git-Spigot-d0d1d87-bc03b6f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by mwkaicz** [comment]
Try turn on ```CompatibilityMode: true``` but it's better to use chests and trapped chests
