### ISSUE TITLE
Movecraft cannot have smaller craft (i.e. torpedos) leave the mother craft

### ISSUE THREAD

**Issue by danielcbailey** [AJCStriker/Movecraft-3#146]
I take control of a ship, it works normally until I try to fire a torpedo with a remote sign or not. The plugin doesn't respond to the action and appears to be doing nothing while the console is being spammed with exceptions. I am running the latest version, the one released on the 22nd of march. The server is using the latest version of spigot from march the 7th. I have disabled crates and I have provided my config below: (The config is still from the previous version but shouldn't make a difference)

Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: true
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: true
FadeWrecksAfter: 0

CONSOLE OUTPUT: (Would repeat forever)

[07:46:16] [Server thread/WARN]: [Movecraft] Task #11481 for Movecraft v3.1.X78 generated an exception
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
	at net.countercraft.movecraft.async.AsyncManager.isRegionBlockedPVP(AsyncManager.java:498) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.processSinking(AsyncManager.java:523) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:851) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_11]

**Comment by mwkaicz** [comment]
Try to update WorldGuard
