### ISSUE TITLE
Async task generated an exception

### ISSUE THREAD

**Issue by eirikh1996** [AJCStriker/Movecraft-3#147]
[22:44:39 ERROR]: [Movecraft] Async Task generated an exception.
[22:44:39 WARN]: java.lang.IllegalStateException: Asynchronous entity world add!
[22:44:39 WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[22:44:39 WARN]: 	at net.minecraft.server.v1_8_R1.World.b(World.java:2590)
[22:44:39 WARN]: 	at net.minecraft.server.v1_8_R1.Chunk.addEntities(Chunk.java:793)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:40)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[22:44:39 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:113)
[22:44:39 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88)
[22:44:39 WARN]: 	at net.countercraft.movecraft.async.detection.DetectionTask.detectBlock(DetectionTask.java:95)
[22:44:39 WARN]: 	at net.countercraft.movecraft.async.detection.DetectionTask.detectSurrounding(DetectionTask.java:232)
[22:44:39 WARN]: 	at net.countercraft.movecraft.async.detection.DetectionTask.excecute(DetectionTask.java:67)
[22:44:39 WARN]: 	at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:44:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:44:39 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:44:39 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:44:39 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by mwkaicz** [comment]
I don't think that it's problem of Movecraft directly, but what version of Movecraft do you have? 

Do you have ```CompatibilityMode: true``` in config file?

**Comment by eirikh1996** [comment]
Yes, but it worked after i found that the craft was adjacent to water

**Comment by mwkaicz** [comment]
I think, that's same problem like here https://github.com/msummers123/Movecraft-3/issues/117

problem is that your craft has water in allowedBlocks and plugin can't detect maximal size of the craft correctly. In normal state plugin should say to you that your craft is too big, instead of this error.
