### ISSUE TITLE
Movecraft full error

### ISSUE THREAD

**Issue by spielbar** [AJCStriker/Movecraft-3#148]
this is the error that is showing me in the console

[18:33:48] [Craft Scheduler Thread - 2/ERROR]: [Movecraft] Async Task generated an exception.
[18:33:48] [Craft Scheduler Thread - 2/WARN]: java.lang.IllegalStateException: Asynchronous entity world add!
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R2.World.b(World.java:2640)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R2.Chunk.addEntities(Chunk.java:820)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getChunkAt(CraftWorld.java:125)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getBlockAt(CraftWorld.java:89)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.countercraft.movecraft.async.detection.DetectionTask.detectBlock(DetectionTask.java:95)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.countercraft.movecraft.async.detection.DetectionTask.detectSurrounding(DetectionTask.java:232)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.countercraft.movecraft.async.detection.DetectionTask.excecute(DetectionTask.java:67)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at net.countercraft.movecraft.async.AsyncTask.run(AsyncTask.java:36)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:33:48] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by mwkaicz** [comment]
Whats your vesrsion of Movecraft? 
Reason of this is probably fact that your craft is connected to some material which could be part of the craft (it's in allowedBlocks, f.e: you have a ship which can contains water but its connected to the lake) so craft can't find end of the craft.  ... but this bug should be fixed in latest public version (except of Subcraft Rotation)

**Comment by spielbar** [comment]
I have the latest version from bukkit.org

**Comment by mwkaicz** [comment]
Ok, can you describe which action you made before this error?

**Comment by spielbar** [comment]
I wrote the sign but then i click on it, it says sometimes that the airskiff is too big.

**Comment by mwkaicz** [comment]
so I suppose that it's normal pilot sign (not Subcraft Rotate).

Error should not be there ( I hoped that we solved this, but I can confirm that in some cases still occures). But: what plugin tells you will be right: Your craft is too big ... that means it's connected to something (land/water) which can be also part of the craft. I think Error is caused from point that Plugins is trying to detect craft on really big mass of blocks which are far far away.  Try to disconect craftt from the land (f.e: via WorldEdit move with it few blocks up, or just destroy land under craft) ... you will see that now it will works. 

Try to compare allowedBlocks in your Airskiff craft file with blocks under your craft to find what blocks causes that.

**Comment by spielbar** [comment]
Ok but now ive got another problem, i can only start to flight, if i cut the land away with worldedit. Why ?

**Comment by mwkaicz** [comment]
Sorry, I don't understand what are u asking now. Don't remove all land, just only which is connected to the craft ... or you can replace it with something else (f.e: stone or grass are mostly not in craft allowedBlocks) ... so when you have grass under craft, you haven't problem. 

If you are talking about something else, please post craft file and some screenshot

**Comment by spielbar** [comment]
If i want to flight with an Airskiff, and i'm standing on a stone floor, i can't move because the plugin says that the craft is obstructed. if i remove the land under the airskiff it starts.
