### ISSUE TITLE
Airships wont move, error in log

### ISSUE THREAD

**Issue by mjcrafter100** [AJCStriker/Movecraft-3#150]
this is what seems to be the error, IDK though, but whenever I pilot a craft, and try to move it, it wont.
It seems to work for other craft though.
sorry for the text, it kinda repeats.
Any idea how to fix? I tried re installing movecraft.
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Multicraft] Skipped 40 lines due to rate limit (200/s)
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:318) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.utils.MapUpdateManager.getBlockDataPacket(MapUpdateManager.java:773) ~[?:?]
21.05 15:22:36 [Server] INFO at net.countercraft.movecraft.items.StorageChestItem.getInventoryOfCrateAtLocation(StorageChestItem.java:56) ~[?:?]
21.05 15:22:36 [Server] INFO java.lang.NullPointerException
21.05 15:22:36 [Server] WARN Task #35 for Movecraft v3.1.X80 generated an exception
21.05 15:22:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot35.jar:git-Spigot-dbe012b-63e28b1]
21.05 15:22:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot35.jar:git-Spigot-dbe012b-63e28b1]

**Comment by mjcrafter100** [comment]
Also, somtimes redstone will turn to stone on random.
