### ISSUE TITLE
Console spam whenever I pilot something

### ISSUE THREAD

**Issue by adamk523** [AJCStriker/Movecraft-3#152]
Right clicked a sign to pilot an airship, and it said "successfully piloted craft" on the player's end but spammed this message in the console non-stop.

[13:48:03] [Server thread/WARN]: [Movecraft] Task #1332 for Movecraft v4.0.1 generated an exception
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
	at net.countercraft.movecraft.async.AsyncManager.isRegionBlockedPVP(AsyncManager.java:503) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.processSinking(AsyncManager.java:562) ~[?:?]
	at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:910) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.7.9-build1543.jar:git-Spigot-1543]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [spigot-1.7.9-build1543.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:638) [spigot-1.7.9-build1543.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot-1.7.9-build1543.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.9-build1543.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.9-build1543.jar:git-Spigot-1543]
	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.9-build1543.jar:git-Spigot-1543]

**Comment by adamk523** [comment]
Forgot to mention, running Spigot 1.7.10 if that makes any difference.

**Comment by mwkaicz** [comment]
It looks like you have some incompatible version of WordGuard. Try update it.
