### ISSUE TITLE
Storage Crates turn into Pistons when placed (error output included)

### ISSUE THREAD

**Issue by 1337ingDisorder** [AJCStriker/Movecraft-3#19]
I can create a Storage Crate using the crafting recipe in the demo video. I get an item that looks like a chest, but its name is "Storage Crate" (in italics). 

So far so good, but when I place that storage crate on a ship (or on the ground or anywhere else) it immediately turns into a piston. It doesn't show the piston head graphic on all sides, it just looks like a standard piston sitting on its side.

If I right-click on the piston I don't get the Storage Crate GUI that it shows in the video, so it's not just a drawing problem -- it's actually replacing the storage crate with a piston.

Really looking forward to getting the storage crates working! :D

Using CraftBukkit Beta Build (1.5.1-R0.2) 

Error output:

2013-04-14 16:59:55 [SEVERE] Could not pass event BlockPlaceEvent to Movecraft v3.1.25
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:107)
        at net.minecraft.server.v1_5_R2.ItemBlock.processBlockPlace(ItemBlock.java:85)
        at net.minecraft.server.v1_5_R2.ItemBlock.interactWith(ItemBlock.java:71)
        at net.minecraft.server.v1_5_R2.ItemStack.placeItem(ItemStack.java:79)
        at net.minecraft.server.v1_5_R2.PlayerInteractManager.interact(PlayerInteractManager.java:386)
        at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:632)
        at net.minecraft.server.v1_5_R2.Packet15Place.handle(SourceFile:58)
        at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
        at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:580)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at net.countercraft.movecraft.items.StorageChestItem.createNewInventory(StorageChestItem.java:64)
        at net.countercraft.movecraft.listener.BlockListener.onBlockPlace(BlockListener.java:47)
        at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at net.countercraft.movecraft.items.StorageChestItem.createNewInventory(StorageChestItem.java:64)
        at net.countercraft.movecraft.listener.BlockListener.onBlockPlace(BlockListener.java:47)
        at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at net.countercraft.movecraft.items.StorageChestItem.createNewInventory(StorageChestItem.java:64)
        at net.countercraft.movecraft.listener.BlockListener.onBlockPlace(BlockListener.java:47)
        at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 19 more

Plugin list:

BetterAlias, QuickShop, CityWorld, WorldEdit, NoCheatPlus, FrameProtect, BattleTracker, Simple-AutoSave, tce, Buycraft, Vault, PlotMe, PlayerHeads, PermissionsEx, CensoredChat, KoolKash, uSkyBlock, WorldGuard, AutoMessage, Lottery, GrowthLimiter, MultiCommand, GoldRush, SkylandsPlus, CrackShot, iDisguise, AutoDropParty, RunAs, Movecraft, Timeismoney, MobArena, Essentials, EssentialsProtect, HeavySpleef, Assassins, Multiverse-Core, EssentialsAntiBuild, PVPPack, EssentialsChat, Factions, ShowCaseStandalone, AutorunCommands, Multiverse-Portals, Multiverse-Inventories, Multiverse-NetherPortals, BattleArena, ArenaCTF

**Comment by Deiscorides** [comment]
Will this bug be fixed?

Running:

Server,
Spigot (git-Spigot-76236cb-62a2169 [Minecraft : 1.8.8] API 1.8.8-r031-SNAPSHOT)
Movecraft 4.0.1 
No other plugins/mods.

Client,
Minecraft 1.8.8
