### ISSUE TITLE
[WARNING] [Movecraft] Task #29 for Movecraft v3.1.31 generated an exception

### ISSUE THREAD

**Issue by paulj1x** [AJCStriker/Movecraft-3#58]
Movecraft v3.1.31
git-Bukkit-1.6.2-R1.0-3-g9532cb6-b2889jnks (MC: 1.6.4) (Implementing API version 1.6.4-R0.1-SNAPSHOT)

2013-09-29 12:01:32 [INFO] [Movecraft] Player colin_the_pug piloted a craft of type Aircraft with size 11 at location: 233 x, 439 z

We now get the following error 2 to 10 times per second, even after restarts without doing anything with Movecraft, made for a 100 MB log file in one day:

2013-09-29 12:01:38 [WARNING] [Movecraft] Task #29 for Movecraft v3.1.31 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_6_R2/CraftChunk
    at net.countercraft.movecraft.utils.MapUpdateManager.run(MapUpdateManager.java:92)
    at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:524)
    at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
    at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
    at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
    at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_6_R2.CraftChunk
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 8 more

**Comment by eirikh1996** [comment]
I get the same warning. Im running movecraft on spigot mc 1.8 and java 1.8

**Comment by mwkaicz** [comment]
Do you have ```CompatibilityMode: true``` in config file?

**Comment by eirikh1996** [comment]
Yes

**Comment by eirikh1996** [comment]
But i have set it to false now. Thanks for that quick response. I really appreciate that

**Comment by mwkaicz** [comment]
CompatibilityMode: true - mostly solves problems with incompatible version of bukkit
What version of Movecraft do you have?
P.S: This repo is out of date, nextime use: https://github.com/msummers123/Movecraft-3/

**Comment by mwkaicz** [comment]
Problem is in your WorldEdit, not in Movecraft. Exactly in coop Movecraft with WE.
I think that you have some older version of WE, try to update it.

**Comment by eirikh1996** [comment]
I use this version of Movecraft: Movecraft V 3.1.X73 
I use this version of WE: WorldEdit 6.0, which is the most recent one, released in december 2014

**Comment by mwkaicz** [comment]
Im not main developer but try update to X74.

if update will doesn't works let me know.

this is last option:
WorldGuardBlockSinkOnPVPPerm: false
WorldGuardBlockMoveOnBuildPerm: false
